services:
  postgres:
    image: postgres:latest
    container_name: book-db-postgres
    ports: [ "5432:5432" ]
    volumes:
      - ./volumes/postgres:var/liv/postgresql/data
    restart: unless-stopped
